### ISSUE TITLE
Dependency badge displayed error when dep vulnerability is 1

### ISSUE THREAD

**Issue by imda-kwokwk** [IMDA-BTG/aiverify#125]
The dependency badge generated by the pre-merge checks GHA displays "error" for stock-plugins when the scan found 1 dependency vulnerability.  It should display 1.  The issue was caused by the pattern matching in the createBadge.py script.

Propose to fix the pattern matching in the createBadge.py script.

**Comment by imda-benedictlee** [comment]
The issue has been fixed with PR#130. Proceeding to Close Issue.
