### ISSUE TITLE
[BUG] LightGBM Model not supported

### ISSUE THREAD

**Issue by normanchia-imda** [IMDA-BTG/aiverify#134]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

Faced an error when trying to upload a LightGBM model. It says that LightGBM is not supported even tho it is indicated as one of the supported framework. 

### Current Behavior

Attached is the error that was shown when uploading. 

<img width="379" alt="Screenshot 2023-07-18 at 6 30 39 PM" src="https://github.com/IMDA-BTG/aiverify/assets/132418893/06c9bd6f-0585-4d4d-8926-f95fe5bffeca">

### Expected Behavior

I was expecting the validation for uploading the model to succeed as it is one of the supported framework indicated. 

### Environment

```markdown
- Operating System and Version: macOS Ventura M1 Chip
- AI Verify Version: v0.9.0
- Any other relevant information (e.g. version of related package dependencies installed):

Did you build using source code or from docker file? If from source code, please provide the below information:
- Python Version:
- Node Version:
- Redis Version:
- Mongo Version: 
- Screen Resolution:
Build using docker file.
```

**Comment by kimeetok** [comment]
Fixed in release [v0.9.2](https://github.com/IMDA-BTG/aiverify/releases/tag/v0.9.2)
