### ISSUE TITLE
[BUG] Dataset and Model will not be available for upload after deselecting and reselecting the same file.

### ISSUE THREAD

**Issue by imda-benedictlee** [IMDA-BTG/aiverify#161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Upload function does not allow the user to upload the same file that they have deselected and reselected. This occurs regardless of whether it is a data file or model file and regardless of data type.

### Current Behavior

The user will upload the file, deselect it via UI, then reselect it again for upload. However, it does not appear available for upload.

### Expected Behavior

The file should appear available for the user to upload.

### Steps To Reproduce

1. Select a file to upload
2. Deselect it by clicking on the X beside the filename
3. Reselect the same file for upload

### Environment

```markdown
- Operating System and Version: Ubuntu 22.04 via Docker 
- AI Verify Version: Branch "origin/v0.9.x"
- Any other relevant information (e.g. version of related package dependencies installed):

Did you build using source code or from docker file? If from source code, please provide the below information:
Docker
```

### Screenshots/ Code snippets

![image](https://github.com/IMDA-BTG/aiverify/assets/118954493/0a9aa56c-5b85-4005-9cd6-1fe03f75a7aa)
![image (2)](https://github.com/IMDA-BTG/aiverify/assets/118954493/567d562f-8c41-4b10-aa80-ec69d59b467b)
![image (1)](https://github.com/IMDA-BTG/aiverify/assets/118954493/e064009a-acb8-4b8b-a802-c15f54f4feec)

### Additional Context

No

**Comment by imda-benedictlee** [comment]
Found an issue where a dataset that is being used on an existing project is unable to be deleted, but is not shown as part of the uploaded dataset @imda-amdlahir

**Comment by imda-amdlahir** [comment]
> Found an issue where a dataset that is being used on an existing project is unable to be deleted, but is not shown as part of the uploaded dataset @imda-amdlahir

@imda-benedictlee - change of plan. Please create a separate issue for this one. We'll close issue 161 first. Raising PR..

**Comment by imda-benedictlee** [comment]
Tested Selecting, Deselecting, Reselecting Dataset. Working as expected.
![image](https://github.com/IMDA-BTG/aiverify/assets/118954493/4bd2dffa-598c-4330-a7fc-8e0da91ca6e9)

Tested Selecting, Deselecting, Reselecting Model. Working as expected.
![image](https://github.com/IMDA-BTG/aiverify/assets/118954493/f68ebb04-3a97-4898-8979-f44ea14c85a5)

Tested Selecting, Deselecting, Reselecting Model for TensorFlow. Issue Persisting:
![image](https://github.com/IMDA-BTG/aiverify/assets/118954493/28b17d67-6549-4d23-9287-af11e0570c38)
