### ISSUE TITLE
[BUG]  Unable to create a project

### ISSUE THREAD

**Issue by Xbluer** [IMDA-BTG/aiverify#163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After entering project information on the project creation page and clicking the [Next] button, an error message is displayed.

![image](https://github.com/IMDA-BTG/aiverify/assets/3921793/1f9a2d90-5c12-43f3-bfb6-961c04879b15)

Browser developer tools indicate network request error.

The domain in the requested URL  is __not__ the server address.

![image](https://github.com/IMDA-BTG/aiverify/assets/3921793/6ca53383-e25c-4602-b1b4-197ec5cfb142)

### Environment

```markdown
- Operating System and Version:  Ubuntu 22.04 via Docker 
- AI Verify Version: release 0.9
- Any other relevant information (e.g. version of related package dependencies installed):

Did you build using source code or from docker file? If from source code, please provide the below information: 
- Python Version:
- Node Version:
- Redis Version:
- Mongo Version: 
- Screen Resolution:

build from docker file
```

**Comment by bijucyborg** [comment]
I have the same issue and I see the following error
WebSocket connection to 'ws://localhost:4000/graphql' failed: 
I'm running the app inside a docker container on AWS.

**Comment by bijucyborg** [comment]
It seems like a CORS issue coz when i create an SSH tunnel and use localhost as the URL the UI works fine. I tried setting environment variables but was unsuccessful. Need to do further investigate.

**Comment by bijucyborg** [comment]
This was my mistake, I forgot to set 
ARG PORTAL_URL=http://ec2-xxx.compute-1.amazonaws.com
ARG WS_URL=ws://ec2-xxx.compute-1.amazonaws.com
in the Dockerfile. I then rebuilt the docker image and started new containers.
Everything works as expected now.

**Comment by imda-benedictlee** [comment]
Hi @Xbluer, thank you for bringing the issue to our attention. Based on the Environment settings and Screenshots that you have provided, I am unable to recreate it on my end, as seen from the screenshot below. Therefore, I would like to check the following with you:

- Is the Docker container hosted on a Cloud Service?
- Are there any additional configurations made to the Docker container and/or image

![image](https://github.com/IMDA-BTG/aiverify/assets/118954493/e7d1b60e-3084-4177-9e49-fc2b21a9dc56)

Hi @bijucyborg, I'm glad to hear that the issue has been resolved for you. However, should you encounter the issue again, feel free to tag me or @kimeetok on this issue thread and we will attend to it as soon as possible.

**Comment by bijucyborg** [comment]
Thanks @kimeetok @imda-benedictlee 
After setting the PORTAL and WS_URL, data upload and model upload work fine. But when I run the tests, its unable to find the assets.
```
2023-08-14 14:57:37,961 [ERROR][app_logger.py::add_to_log(126)] [task.py:process(214)]: There was an error parsing the provided task arguments: The model file is not found;
2023-08-14 14:57:37,962 [INFO][app_logger.py::add_to_log(116)] [task_result.py:set_progress(114)]: The current task completion progress is 100
2023-08-14 14:57:37,962 [INFO][app_logger.py::add_to_log(116)] [task_result.py:set_status(146)]: The current task has changed status to TaskStatus.ERROR
2023-08-14 14:57:37,964 [INFO][app_logger.py::add_to_log(116)] [worker.py:_send_update(614)]: The update sent successfully: task:64d9d06189d593f07c8e7891-64d9d06189d593f07c8e7936:{'type': 'TaskResponse', 'status': 'Error', 'elapsedTime': 0, 'startTime': '2023-08-14T14:57:37.954110', 'output': '', 'errorMessages': '[{"category": "SYSTEM_ERROR", "code": "FSYSx00138", "description": "There was an error parsing the provided task arguments: The model file is not found;", "severity": "warning", "component": "task.py"}]', 'logFile': '/app/aiverify/test-engine-app/logs/task:64d9d06189d593f07c8e7891-64d9d06189d593f07c8e7936.log', 'taskProgress': 100}
2023-08-14 14:57:37,964 [INFO][app_logger.py::add_to_log(116)] [worker.py:_send_acknowledgement(659)]: The acknowledgement sent successfully - 1691996257953-0
2023-08-14 14:57:37,964 [INFO][app_logger.py::add_to_log(116)] [task.py:cleanup(104)]: The system has received notification to clean up task
```
I'm running AI Verify on docker on an EC2 instance, so the URL is not localhost. I have opened ports 3000 and 4000 for this application, any other ports required??

**Comment by Xbluer** [comment]
@bijucyborg @imda-benedictlee Thank you for your reply.

 I have solved this problem by changing Dockerfile and rebuilding the docker image.

> This was my mistake, I forgot to set ARG PORTAL_URL=http://ec2-xxx.compute-1.amazonaws.com ARG WS_URL=ws://ec2-xxx.compute-1.amazonaws.com in the Dockerfile. I then rebuilt the docker image and started new containers. Everything works as expected now.↳

**Comment by Xbluer** [comment]
@imda-benedictlee 
>Is the Docker container hosted on a Cloud Service?   

Yes. I access  the application from a remote browser.

>Are there any additional configurations made to the Docker container and/or Docker Image?

Before I post this issue , I did not make and additional configurations.

---
It would be great if the documentation could include instructions for modifying the PORTAL_URL and WS_URL parameters before creating the Docker image.
Is it possible to consider making PORTAL_URL and WS_URL runtime parameters for the Docker container rather than image build parameters?

**Comment by bijucyborg** [comment]
> Thanks @kimeetok @imda-benedictlee After setting the PORTAL and WS_URL, data upload and model upload work fine. But when I run the tests, its unable to find the assets.
> 
> ```
> 2023-08-14 14:57:37,961 [ERROR][app_logger.py::add_to_log(126)] [task.py:process(214)]: There was an error parsing the provided task arguments: The model file is not found;
> 2023-08-14 14:57:37,962 [INFO][app_logger.py::add_to_log(116)] [task_result.py:set_progress(114)]: The current task completion progress is 100
> 2023-08-14 14:57:37,962 [INFO][app_logger.py::add_to_log(116)] [task_result.py:set_status(146)]: The current task has changed status to TaskStatus.ERROR
> 2023-08-14 14:57:37,964 [INFO][app_logger.py::add_to_log(116)] [worker.py:_send_update(614)]: The update sent successfully: task:64d9d06189d593f07c8e7891-64d9d06189d593f07c8e7936:{'type': 'TaskResponse', 'status': 'Error', 'elapsedTime': 0, 'startTime': '2023-08-14T14:57:37.954110', 'output': '', 'errorMessages': '[{"category": "SYSTEM_ERROR", "code": "FSYSx00138", "description": "There was an error parsing the provided task arguments: The model file is not found;", "severity": "warning", "component": "task.py"}]', 'logFile': '/app/aiverify/test-engine-app/logs/task:64d9d06189d593f07c8e7891-64d9d06189d593f07c8e7936.log', 'taskProgress': 100}
> 2023-08-14 14:57:37,964 [INFO][app_logger.py::add_to_log(116)] [worker.py:_send_acknowledgement(659)]: The acknowledgement sent successfully - 1691996257953-0
> 2023-08-14 14:57:37,964 [INFO][app_logger.py::add_to_log(116)] [task.py:cleanup(104)]: The system has received notification to clean up task
> ```
> 
> I'm running AI Verify on docker on an EC2 instance, so the URL is not localhost. I have opened ports 3000 and 4000 for this application, any other ports required??

This is also solved, was some issue because of all the testing I did. I created a new instance and new container and the tests go through as well.

**Comment by kimeetok** [comment]
Thanks @Xbluer and @bijucyborg , we have raised #169 to explore the suggestions made :)
