### ISSUE TITLE
Dynamic Height for Canvas Widgets

### ISSUE THREAD

**Issue by thomasimda** [IMDA-BTG/aiverify#53]
Extend dynamic height support to enable "overflow" support where a widget contents extend beyond the set size of the widget.

Current Behaviour: Content extending beyond the widget will be truncated.

Target Behaviour: Content extending beyond the widget can be set to dynamically resize.

**Comment by imda-peckyoke** [comment]
To indicate that a widget is dynamic height, set property dynamicHeight to true in the widget meta data.

Restrictions on dynamic height widget:
- Must be the bottom most widget, i.e. there cannot be any static widgets below it.
- Only one dynamic height widget per page.

**Comment by imda-peckyoke** [comment]
TODO after discussion on 19 June 2023:
* process checklist - convert to use dynamic height widgets
* visual indicator on canvas when try to drag dynamic height on top of other static widgets
* show visually on canvas the dynamic height widgets
* bug fixes on canvas
